title: Hitesh's Portfolio
logo: assets/img/professional_pic.jpeg
theme: jekyll-theme-minimal
description: Full Stack Java Developer with expertise in Java, Spring Boot, Angular, React, and Cloud Services
author: Hitesh S
show_experience: false
